{% set name = "glmnet" %}
{% set version = "2.2.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: aaaa
  patches:
    - setup.py.patch

build:
  number: 5
  skip: True  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - python
    - numpy
    - scikit-learn >=0.18.0
    - scipy >=0.14.1
    - joblib >=0.14.1
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scikit-learn >=0.18.0
    - scipy >=0.14.1
    - joblib >=0.14.1

test:
  imports:
    - glmnet

about:
  home: https://github.com/civisanalytics/python-glmnet
  license: GPL-2.0
  license_family: GPL
  summary: 'Python wrapper for glmnet'
  dev_url: https://github.com/civisanalytics/python-glmnet
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mheilman
    - salilgupta1
    - colemandsmith
    - jseabold
