{% set name = "glmnet" %}
{% set version = "2.2.1" %}
{% set md5 = "ca6e15cd110d732245af7159aff61878" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}
  patches:
    - setup.py.patch

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - python
    - numpy >=1.9.2
    - scikit-learn >=0.18.0
    - scipy >=0.14.1
    - joblib >=0.14.1
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scikit-learn >=0.18.0
    - scipy >=0.14.1
    - joblib >=0.14.1

test:
  imports:
    - glmnet

about:
  home: https://github.com/civisanalytics/python-glmnet
  license: GPL-2.0
  license_family: GPL
  summary: 'Python wrapper for glmnet'
  dev_url: https://github.com/civisanalytics/python-glmnet
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mheilman
    - salilgupta1
    - colemandsmith
    - jacksonllee
    - jseabold
    - beckermr
    - stephen-hoover
