{% set name = "glmnet" %}
{% set version = "2.1.0" %}
{% set md5 = "0660fdde3a965b9d6249070904c1affd" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}
  patches:
    - setup.py.patch

build:
  number: 1000
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - python
    - numpy 1.11.*
    - scikit-learn >=0.18.0
    - scipy >=0.14.1
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scikit-learn >=0.18.0
    - scipy >=0.14.1

test:
  imports:
    - glmnet

about:
  home: https://github.com/civisanalytics/python-glmnet
  license: GPL-2.0
  license_family: GPL
  summary: 'Python wrapper for glmnet'
  dev_url: https://github.com/civisanalytics/python-glmnet
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jseabold
    - beckermr
