appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: 1yASBq6SgNnYX5qKMBOosnMMqRBLo54zVzzXmId3E3preL1hrcRStS8o20tvMCBdnUdxfGcty3aVSLbCHSyd/wt1+Pk9W+G0arVzlnwAbJYhqFD+leDP8b22qB0b/CZJTTF920TLkATMZUAcIVCxrqfq325iZJyAY7z/d7KGNMPKTVE+GnRnqAKrg2JNWEdzIdoSm/8jTlADpY6WqBLZvvUWAKTvvCudrlTXFTnJ4TglcZMFZiR37pcdvB4BKw51R3AhRm0Hk58ojqdmOLGWtue6J/IBgAhPDELybrKHauL5MzbM9Q8AXzoxLwIy7o84kYjN97jqQ/mbcMvRDsKFFYPlemUqyi6qBJaHXsGq0dCVmv0QdakIgnEwQV+51CQQ1K3BeAuwPBendTlyQp9gil6C55twqA4ncSPqRoiFIjoO/KlJ8dkffY0p/D3uiTJSc6nFOuFnqyAjFi248AQwTh3XoH67fhY7HXB52n1mPtu6Plzbnvrj/aVMpNw20kh0qBVw6EoeSIJkCFfKQrgom3YSZDLuSeEEYdSwAs8bYjrLgfBzIdIUoiavsbGt9EWtRoLc8ULjpte25lLLXIhg4y9uvPwwvUpyTvZb6/wbGZNjQGJ1/dbboTCNSqXOMuHpWe0HqOobGtKVoJxgGd9icWlfoCBOn3AivcqNh5sbzm4=}
conda_forge_output_validation: true
